### PR TITLE
Heroku Deploy Button

### PR DESCRIPTION
**Pull request by zh**
After pressing the button user will be redirected to the Heroku settings screen, where he can set application name, mnemonic and distribute secret (see the attached screenshot).

heroku_settings
)

You can see already working button in [my repository clone](https://github.com/zh/slp-faucet)

Example of application, deployed with the button (an error message for empty faucet is displayed, but I have it on my local machine too, so maybe some setting is missing...): [https://slp-faucet-example.herokuapp.com/](https://slp-faucet-example.herokuapp.com/)

### CODE REVIEW

**Comment by jcramer** [comment]
Excellent, I will review shortly.

**Comment by jcramer** [comment]
Just a few comments:

1. Let's set up the button so we can test it out A-Z before merging.  It looks like currently when I click the button it's looking at the "simpleledger/slp-faucet" repo.  Once it's working in your forked branch you can update the repo path as a final step before merging.  Please test the faucet out using a token that you've created, and paste a link here showing your faucet running and working.

2. Please remove the default values in `app.json`, they should start out blank for the user to fill out.

3. We should provide better descriptions for each environment variable to help the user get started and inform the user of any potential risks.  We need to warn the user about the risk of storing his mnemonic seed phrase on a 3rd party system which could lead to loss of funds.

For example, 

    "MNEMONIC": {
       "description": "WARNING: Running this application requires that you store your private keys (12-word mnemonic seed phrase) on a 3rd party system, i.e., Heroku's servers, which may cause your funds to be hacked or stolen.  We are not responsible for any loss of funds as a result of your use or misuse of this faucet.  Do not store large values or amounts on the mnemonic seed phrase in order to minimize your risk for financial loss. You should generate a brand new 12-word seed phrase to use exclusively for this faucet, this is your secret mnemonic seed phrase that will be used to automatically distribute your token when users paste their SLP address.  We recommend using Electron Cash SLP Edition standard wallet type to generate and monitor this faucet which uses an HD derivation path m/44'/245'/0'.  You can download the Electron Cash SLP wallet at: https://simpleledger.cash/project/electron-cash-slp-edition.  If you don't know or understand what a mnemonic seed phrase is you can learn more at: https://en.bitcoin.it/wiki/Seed_phrase",
       "value": ""
     },
     "TOKENID": {
       "description": "The token id associated with the SLP token that you would like this faucet to distribute",
       "value": ""
     },
     "TOKENQTY": {
       "description": "The quantity of token to be distributed to each faucet visitor",
       "value": ""
     },
     "DISTRIBUTE_SECRET": {
       "description": "The secret word used to initiate the faucet after you have funded one of the faucet's addresses with both Bitcoin Cash and your SLP token.  This will also need to be used when the faucet runs out of Bitcoin Cash or tokens.",
       "value": ""
     }

**Comment by jcramer** [comment]
FYI: `error: Faucet is temporarily empty :(` means that the faucet has not been properly initiated.  You need to fund the wallet.  Per the README:

"Use Electron Cash SLP or other SLP wallet to store faucet token & BCH coins, then use the mnemonic for that wallet for the faucet in the MNEMONIC environmental variable."

**Comment by zh** [comment]
OK. I fixed the description in commit# 07e38f9. Also URL in the button is set to my forked repo branch

**Comment by zh** [comment]
> FYI: `error: Faucet is temporarily empty :(` means that the faucet has not been properly initiated. You need to fund the wallet. Per the README:
> 
> "Use Electron Cash SLP or other SLP wallet to store faucet token & BCH coins, then use the mnemonic for that wallet for the faucet in the MNEMONIC environmental variable."

Hm, this is strange... It was already used wallet, with BCH (about $2) and 100 SLP tokens (the TOKENID was set for them)...

**Pull request merged**
